version: '3.3'
services:
 sonarqube:
  image: sonarqube:8.9.7-community
  ports:
  - "9003:9003"
  - "9094:9094"
  volumes:
  - 'SonarQube_data:/opt/SonarQube/data'
  - 'SonarQube_extensions:/opt/SonarQube/extensions'
  - 'SonarQube_logs:/opt/SonarQube/logs'
 nexus:
  image: sonatype/nexus3
  ports:
  - "8082:8082"
  volumes:
  - 'nexus-data:/nexus-data'
volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus-data:
